---
- name: listen for tfc events
  hosts: all

  sources:
    - name: tfc notifications webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: pending status rule
      condition: event.payload.notifications[0].run_status == "pending"
      action:
        debug:
          msg: "TFC run is pending"

    - name: planning status rule
      condition: event.payload.notifications[0].run_status == "planning"
      action:
        debug:
          msg: "TFC run is planning"

    - name: applying status rule
      condition: event.payload.notifications[0].run_status == "applying"
      action:
        debug:
          msg: "TFC run is applying"

    - name: applied status rule
      condition: event.payload.notifications[0].run_status == "applied"
      actions:
        - debug:
            msg: "TFC run is applied"
        - run_job_template:
            name: Demo Job Template
            organization: Default

    - name: catchall status rule
      condition: event.payload.notifications[0].run_status not in ["pending", "planning", "applying", "applied"]
      action:
        print_event:
          pretty: true
